// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppreatagejjntctczdvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwcmVhdGFnZWpqbnRjdGN6ZHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNDU4NjksImV4cCI6MjA3NDcyMTg2OX0.qN2LGzCpfSo_7NsyIvHAqc6EmOnLhQi8H8PpYfPayFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});